# -*- coding: utf-8 -*-
"""PythonTestNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQ7NflriKw9Mq60C4N5Mf0GtxaOs6Asj
"""

"""
Number Guessing Game

My first Python project.

Features:
- Difficulty selection
- Input validation
- Higher / Lower hints
- Guess counter

Created by Metu
"""

import random

# Here we check if the given input is a valid integere
def check_for_integer(prompt):
  while True:
    try:
      check_number = int(input(prompt))
      break
    except ValueError:
      print("That is not a valid integer")
  return check_number

# Here we check the difficulty level
def difficulty_selection():
    print("Please choose a difficulty")
    print("1   Easy (0-10)")
    print("2   Normal (0-100)")
    print("3   Hard (0-1000)")

    while True:
        difficulty = check_for_integer("Choice: ")

        if difficulty not in [1, 2, 3]:
            print("Please enter 1, 2 or 3.")
            continue
        return difficulty

def game_loop():
  number_of_guesses = 0
  difficulty = difficulty_selection()
  random_number = random.randint(0,10**difficulty)
  while True:
    guess_number = check_for_integer("Please guess a number: ")
    if random_number != guess_number:
      if guess_number > random_number:
        print("Too High")
        number_of_guesses += 1
        continue
      elif guess_number < random_number:
        print("Too Low")
        number_of_guesses += 1
        continue
    number_of_guesses += 1
    print("YOU WON")
    print(f"The number was {random_number} ,and you guessed it in {number_of_guesses} tries")
    break